services:
  client4_container:
    build: .
    container_name: client4_container
    privileged: true
    ports:
      - "6004:6004"  
    volumes:
      - .:/app
    networks:
      client-network:
        ipv4_address: 192.168.100.14
        mac_address: 02:42:c0:a8:64:04
    tty: true

networks:
  client-network:
    external: true
