    services:
  client7_container:
    build: .
    container_name: client7_container
    privileged: true
    ports:
      - "6007:6007"  
    volumes:
      - .:/app
    networks:
      client-network:
        ipv4_address: 192.168.100.17
        mac_address: 02:42:c0:a8:64:07
    tty: true

networks:
  client-network:
    external: true
